app = "bedcrin"
primary_region = "lhr"

[build]
image = "ghcr.io/fatedier/frps:v0.58.1"

[[services]]
  internal_port = 7000
  protocol = "tcp"

  [[services.ports]]
    port = 7000
    handlers = []

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[[services]]
  internal_port = 7000
  protocol = "udp"

  [[services.ports]]
    port = 7000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
